[package]
name = "chord-madness"
version = "0.1.0"
edition = "2021"

[lib]
name = "colorize"
path = "src/lib/colorize.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"